# Generated by Django 4.2.7 on 2024-11-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarifas', '0002_tarifa_descripcion_tarifa_fecha_fin_vigencia'),
        ('medidores', '0001_initial'),
        ('usuarios', '0002_alter_usuario_correo_alter_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('medidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medidores.medidor')),
                ('tarifa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarifas.tarifa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'medidor', 'mes')},
            },
        ),
    ]
