# Generated by Django 4.2.7 on 2024-11-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0001_initial'),
        ('consumos', '0002_alter_consumo_unique_together_alter_consumo_medidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='medidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medidores.medidor'),
        ),
    ]
