# Generated by Django 4.2.7 on 2024-11-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_correo_alter_usuario_direccion_and_more'),
        ('medidores', '0001_initial'),
        ('tarifas', '0005_remove_tarifa_nombre'),
        ('consumos', '0003_alter_consumo_medidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='medidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medidores.medidor'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='tarifa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together={('usuario', 'medidor', 'mes')},
        ),
    ]
