# Generated by Django 4.2.7 on 2024-11-16 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0005_remove_tarifa_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medidores', '0001_initial'),
        ('consumos', '0005_alter_consumo_medidor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumo',
            options={'ordering': ['-mes']},
        ),
        migrations.RenameField(
            model_name='consumo',
            old_name='fecha_registro',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='consumo',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='consumo',
            name='consumo_registrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumo',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='medidores.medidor'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarifas.tarifa'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to=settings.AUTH_USER_MODEL),
        ),
    ]
