# Generated by Django 4.2.7 on 2024-11-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0006_alter_consumo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumo',
            options={},
        ),
    ]
