# Generated by Django 4.2.7 on 2024-11-18 02:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0005_remove_tarifa_nombre'),
        ('consumos', '0008_alter_consumo_options_alter_consumo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consumo',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='cantidad_consumida',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fecha_consumo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='tarifa_aplicada',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa'),
            preserve_default=False,
        ),
    ]
