# Generated by Django 4.2.7 on 2024-11-23 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0002_alter_medidor_codigo_serial_alter_medidor_estado_and_more'),
        ('usuarios', '0003_alter_usuario_nombre_alter_usuario_rut'),
        ('tarifas', '0005_remove_tarifa_nombre'),
        ('consumos', '0009_alter_consumo_options_alter_consumo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='cantidad_consumida',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad consumida registrada en metros cúbicos.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fecha_consumo',
            field=models.DateField(help_text='Fecha en que se registró el consumo.'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Fecha en la que se registró este consumo.'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='medidor',
            field=models.ForeignKey(help_text='Medidor relacionado con el consumo.', on_delete=django.db.models.deletion.CASCADE, to='medidores.medidor'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='tarifa_aplicada',
            field=models.ForeignKey(help_text='Tarifa activa en la fecha del consumo.', on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario asociado al consumo.', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
