# Generated by Django 4.2.7 on 2024-11-23 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0005_remove_tarifa_nombre'),
        ('usuarios', '0003_alter_usuario_nombre_alter_usuario_rut'),
        ('medidores', '0002_alter_medidor_codigo_serial_alter_medidor_estado_and_more'),
        ('consumos', '0010_alter_consumo_cantidad_consumida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='cantidad_consumida',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fecha_consumo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidores.medidor'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='tarifa_aplicada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
