# Generated by Django 4.2.7 on 2024-11-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0005_alter_medidor_estado_alter_medidor_usuario'),
        ('tarifas', '0005_remove_tarifa_nombre'),
        ('usuarios', '0003_alter_usuario_nombre_alter_usuario_rut'),
        ('consumos', '0011_alter_consumo_cantidad_consumida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumo',
            options={'verbose_name': 'Consumo', 'verbose_name_plural': 'Consumos'},
        ),
        migrations.AlterField(
            model_name='consumo',
            name='cantidad_consumida',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad de agua consumida en metros cúbicos (m³).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fecha_consumo',
            field=models.DateField(help_text='Fecha en que se realizó el consumo.'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se registró el consumo.'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='medidor',
            field=models.ForeignKey(help_text='Medidor asociado a este consumo.', on_delete=django.db.models.deletion.CASCADE, to='medidores.medidor'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='tarifa_aplicada',
            field=models.ForeignKey(help_text='Tarifa aplicada al consumo.', on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario al que pertenece este consumo.', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddConstraint(
            model_name='consumo',
            constraint=models.UniqueConstraint(fields=('medidor', 'fecha_consumo'), name='unique_consumo_por_fecha'),
        ),
    ]
