# Generated by Django 4.2.7 on 2025-11-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0012_alter_consumo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaRaw',
            fields=[
                ('id_lectura', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_medidor', models.TextField(db_column='id_medidor', verbose_name='Serial ESP32')),
                ('ts_utc', models.DateTimeField(verbose_name='Fecha/Hora')),
                ('pulsos_periodo', models.IntegerField()),
                ('caudal_lpm_prom', models.DecimalField(decimal_places=3, max_digits=10)),
                ('litros_periodo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('litros_total', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Lectura Acumulada')),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bateria_v', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('envio_ok', models.BooleanField()),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Lectura Cruda (IoT)',
                'verbose_name_plural': 'Lecturas Crudas (IoT)',
                'db_table': 'medidas',
                'ordering': ['-ts_utc'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='consumo',
            name='cantidad_consumida',
            field=models.DecimalField(decimal_places=2, help_text='Lectura del medidor en metros cúbicos (m³).', max_digits=10),
        ),
    ]
