# Generated by Django 4.2.7 on 2024-11-14 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$', 'Formato de RUT inválido')])),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
