"""
Django settings for gestion_cobros project.

Generated by 'django-admin startproject' using Django 4.2.7.

This file has been adapted for deployment (Railway) using environment variables
for secret management, database URL, allowed hosts and CSRF trusted origins.
"""

import os
from pathlib import Path
from decimal import Decimal

BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------
# Basic / security
# --------------------------------------------------------------------
# Secret key: use env var in production, fallback to the local one for dev only
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-q#-bca#4vby5raltrj1!@)w0)%w72wn5#xvz&$mxrsrl9m=jrj"
)

# DEBUG from env (default False in production)
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes")

# ALLOWED_HOSTS via env, comma separated. Default to localhost for dev.
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# --------------------------------------------------------------------
# Application definition
# --------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_select2',  # Para select2 en formularios

    # Aplicaciones locales
    'usuarios',
    'roles',
    'medidores',
    'tarifas',
    'consumos',
    'registro_cuentas',
    'login',
    'reportes',
    'widget_tweaks',
    'boletas',
    'django.contrib.humanize',
]

AUTH_USER_MODEL = 'registro_cuentas.Cuenta'

LOGIN_REDIRECT_URL = '/roles/redireccion/'
LOGOUT_REDIRECT_URL = '/login/'

# --------------------------------------------------------------------
# Static files
# --------------------------------------------------------------------
# URL for static files
STATIC_URL = '/static/'

# Directory where collectstatic will collect to
STATIC_ROOT = BASE_DIR / "staticfiles"

# Optional: folder(s) used during development for static assets
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# Use WhiteNoise to serve static files in production
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_cobros.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # añade rutas si usas templates fuera de apps
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_cobros.wsgi.application'

# --------------------------------------------------------------------
# Database
# --------------------------------------------------------------------
# The settings prefer a DATABASE_URL environment variable (12-factor).
# If DATABASE_URL is not present, fall back to explicit env vars or to the
# original local Postgres config previously included.
if os.environ.get("DATABASE_URL"):
    # try to use dj_database_url if available, otherwise expect DATABASE_URL to be parsed externally
    try:
        import dj_database_url  # type: ignore
        DATABASES = {
            'default': dj_database_url.parse(os.environ.get("DATABASE_URL"), conn_max_age=600)
        }
    except Exception:
        # simple fallback: DATABASE_URL present but dj_database_url not installed;
        # let Django try to use it via ENGINE/url (some deploy systems support it).
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'HOST': os.environ.get('DB_HOST', 'localhost'),
                'NAME': os.environ.get('DB_NAME', 'postgres'),
                'USER': os.environ.get('DB_USER', 'postgres'),
                'PASSWORD': os.environ.get('DB_PASSWORD', ''),
                'PORT': os.environ.get('DB_PORT', '5432'),
            }
        }
else:
    # Development / default values (you had a Supabase pooler example)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

# --------------------------------------------------------------------
# CSRF and security settings
# --------------------------------------------------------------------
# CSRF trusted origins must include the exact scheme (https://...) for deployed domains
CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "http://127.0.0.1:8000"
).split(",")

# If your app sits behind a proxy/load-balancer (Railway), use this:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies secure flags: enable in production (when DEBUG is False)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# HSTS (optional, enable only in production)
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Other recommended security flags
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# --------------------------------------------------------------------
# Password validation
# --------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------------------------
# Internationalization / timezone
# --------------------------------------------------------------------
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# --------------------------------------------------------------------
# Static & default primary key
# --------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------------------
# Logging (simple, useful for Railway)
# --------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# --------------------------------------------------------------------
# Development convenience: if DEBUG True, allow cookies over http for local dev
# --------------------------------------------------------------------
if DEBUG:
    # allow localhost origins by default in debug
    if "127.0.0.1:8000" not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS += ["http://127.0.0.1:8000", "http://localhost:8000"]
    # keep cookies non-secure locally
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
