# Generated by Django 4.2.7 on 2024-11-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0011_alter_consumo_cantidad_consumida_and_more'),
        ('boletas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='consumo',
        ),
        migrations.AddField(
            model_name='boleta',
            name='consumo_fin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletas_fin', to='consumos.consumo'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='consumo_inicio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletas_inicio', to='consumos.consumo'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='consumo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='tarifa_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
