# Generated by Django 4.2.7 on 2024-11-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0011_alter_consumo_cantidad_consumida_and_more'),
        ('boletas', '0002_remove_boleta_consumo_boleta_consumo_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='consumo_fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletas_fin', to='consumos.consumo'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='consumo_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletas_inicio', to='consumos.consumo'),
        ),
    ]
