# Generated by Django 4.2.7 on 2024-11-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('operario', 'Operario')], default='operario', help_text='Seleccione el rol asignado a esta cuenta', max_length=50),
        ),
    ]
