# Generated by Django 4.2.7 on 2024-11-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('usuario', 'Usuario'), ('operario', 'Operario')], max_length=50, unique=True)),
            ],
        ),
    ]
