# Generated by Django 4.2.7 on 2024-11-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_cuentas', '0002_alter_cuenta_rol'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
