# Generated by Django 4.2.7 on 2024-11-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_nombre_alter_usuario_rut'),
        ('medidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='codigo_serial',
            field=models.CharField(help_text='Código serial único del medidor.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', help_text='Estado actual del medidor.', max_length=20),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='fecha_instalacion',
            field=models.DateField(blank=True, help_text='Fecha en la que se instaló el medidor.', null=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se registró el medidor.'),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario al que está asignado este medidor.', on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='usuarios.usuario'),
        ),
    ]
