# Generated by Django 4.2.7 on 2024-11-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_nombre_alter_usuario_rut'),
        ('medidores', '0003_alter_medidor_options_alter_medidor_codigo_serial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medidor',
            options={},
        ),
        migrations.AlterField(
            model_name='medidor',
            name='codigo_serial',
            field=models.CharField(help_text='Código serial único del medidor.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='usuarios.usuario'),
        ),
    ]
