# Generated by Django 4.2.7 on 2024-11-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_nombre_alter_usuario_rut'),
        ('medidores', '0004_alter_medidor_options_alter_medidor_codigo_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento'), ('danado', 'Dañado')], default='activo', help_text='Estado actual del medidor.', max_length=20),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario al que está asignado este medidor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='usuarios.usuario'),
        ),
    ]
