# Generated by Django 4.2.7 on 2024-11-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional de la tarifa'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='fecha_fin_vigencia',
            field=models.DateField(blank=True, help_text='Fecha en la que la tarifa dejó de estar vigente', null=True),
        ),
    ]
