# Generated by Django 4.2.7 on 2024-11-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0002_tarifa_descripcion_tarifa_fecha_fin_vigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='nombre',
        ),
    ]
